name: ☁ ┆ Atualizar ambiente de produção

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2.3.1
      - name: Versão do Node.js utilizada -  ${{ matrix.node-version }} ⚙️
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Instalação de dependências 🔧
        run: yarn install

      - name: Construindo aplicação 🏗️
        run: yarn build
        env:
          CI: false
      - name: 🔑 Conigurando chave AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET_DEVELOP_SPA }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_USER_DEPLOY_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_USER_DEPLOY_ACCESS_SECRET }}
          SOURCE_DIR: './dist/spa'

      - name: Atualizando distribuiçoes no CloudFront
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_ID }} --paths "/*"

  discord-message:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Enviando título da mensagem no Discord
        env:
          DISCORD_WEBHOOK: https://discord.com/api/webhooks/${{ secrets.WEBHOOK_ID }}/${{ secrets.WEBHOOK_TOKEN }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'Um novo commit foi pushado em `{{ EVENT_PAYLOAD.repository.full_name }}`. O ambiente https://backy.ccicomp.com.br foi atualizado.'
      - name: Enviando mensagem no Discord
        env:
          DISCORD_WEBHOOK: https://discord.com/api/webhooks/${{ secrets.WEBHOOK_ID }}/${{ secrets.WEBHOOK_TOKEN }}
        uses: Ilshidur/action-discord@master
